version: "3.9"

services:
  coreyt:
    build: .
    container_name: coreyt_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg2://coreyt:coreyt@postgres:5432/coreyt_db

  postgres:
    image: postgres:16
    container_name: coreyt_postgres
    restart: always
    environment:
      POSTGRES_USER: coreyt
      POSTGRES_PASSWORD: coreyt
      POSTGRES_DB: coreyt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: